-- Baseline schema for The Staff Project (Epic 0 + Epic 1 employee identity slice).
-- Flyway owns the schema from this point on; Hibernate only validates.
CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    job_title VARCHAR(255),
    department VARCHAR(255),
    phone VARCHAR(255),
    archived BOOLEAN DEFAULT FALSE
);
