-- Interaction table for TSP-20 (Epic 2).
-- Links an author (current user) and a subject employee. Self-interactions are valid (author = subject).
CREATE TABLE interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    note TEXT NOT NULL,
    type VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    CONSTRAINT fk_interaction_author FOREIGN KEY (author_id) REFERENCES employees(id),
    CONSTRAINT fk_interaction_subject FOREIGN KEY (subject_id) REFERENCES employees(id)
);

CREATE INDEX idx_interaction_author ON interactions(author_id);
CREATE INDEX idx_interaction_subject ON interactions(subject_id);
