-- Portfolio tables for Epic 4 (TSP-5): education, projects, and showcase links.
-- Each row is owned by an employee via a plain foreign key; ON DELETE CASCADE keeps
-- portfolio data in sync with the parent employee.

CREATE TABLE portfolio_education (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    institution VARCHAR(255) NOT NULL,
    qualification VARCHAR(255) NOT NULL,
    field_of_study VARCHAR(255),
    start_year INTEGER,
    end_year INTEGER,
    description TEXT,
    CONSTRAINT fk_portfolio_education_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE TABLE portfolio_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    start_date DATE,
    end_date DATE,
    url VARCHAR(1024),
    CONSTRAINT fk_portfolio_projects_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

CREATE TABLE portfolio_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    label VARCHAR(255) NOT NULL,
    url VARCHAR(1024) NOT NULL,
    sort_order INTEGER DEFAULT 0,
    CONSTRAINT fk_portfolio_links_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);
