-- Task table for TSP-24 to TSP-28 (Epic 3).
-- relatesTo = subject employee; createdBy = employee who logged it; fromInteractionId = optional link.
-- assignee (T5 extension) = who should action it, distinct from relatesTo.
CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    relates_to_id BIGINT NOT NULL,
    created_by_id BIGINT NOT NULL,
    from_interaction_id BIGINT,
    due_date DATE,
    assignee_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_task_relates_to FOREIGN KEY (relates_to_id) REFERENCES employees(id),
    CONSTRAINT fk_task_created_by FOREIGN KEY (created_by_id) REFERENCES employees(id),
    CONSTRAINT fk_task_assignee FOREIGN KEY (assignee_id) REFERENCES employees(id),
    CONSTRAINT fk_task_interaction FOREIGN KEY (from_interaction_id) REFERENCES interactions(id)
);

CREATE INDEX idx_task_relates_to ON tasks(relates_to_id);
CREATE INDEX idx_task_created_by ON tasks(created_by_id);
CREATE INDEX idx_task_assignee ON tasks(assignee_id);
