-- Skills register tables for Epic 5 (TSP-6).
-- skill: canonical deduplicated reference entity (D5).
-- employee_skill: links an employee to a skill with user-entered years.
-- employee_skill_project: join table used to derive projectCount (D1 — never stored).

CREATE TABLE skill (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Case-insensitive unique constraint on skill name (D5 / D-SK2).
CREATE UNIQUE INDEX uq_skill_name_lower ON skill (LOWER(name));

CREATE TABLE employee_skill (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT  NOT NULL,
    skill_id    BIGINT  NOT NULL,
    years       INTEGER NOT NULL,
    CONSTRAINT fk_employee_skill_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT fk_employee_skill_skill    FOREIGN KEY (skill_id)    REFERENCES skill(id),
    CONSTRAINT uq_employee_skill          UNIQUE (employee_id, skill_id)
);

CREATE INDEX idx_employee_skill_employee ON employee_skill(employee_id);
CREATE INDEX idx_employee_skill_skill    ON employee_skill(skill_id);

-- Join table for projectCount derivation (D1 / D-SK4).
CREATE TABLE employee_skill_project (
    employee_skill_id BIGINT NOT NULL,
    project_id        BIGINT NOT NULL,
    PRIMARY KEY (employee_skill_id, project_id),
    CONSTRAINT fk_esp_employee_skill FOREIGN KEY (employee_skill_id) REFERENCES employee_skill(id) ON DELETE CASCADE,
    CONSTRAINT fk_esp_project        FOREIGN KEY (project_id)        REFERENCES portfolio_projects(id) ON DELETE CASCADE
);
